### ISSUE TITLE
Create means to visualize data entering the net

### ISSUE THREAD

**Issue by MarekSebo** [Cognexa/cxflow#124]
possible solution:
* [ ] create a VisualizableDataset class that will enable user to visualize the data and corresponding labels via terminal `cxflow dataset visualize ....`

**Comment by blazekadam** [comment]
Closing as it would be too complicated atm
- it would require adding opencv or similar image lib to the requirements
- there are many variables to be configured (stream names, source names, scales for each source) in order to make it truly general. that would be too confusing

To achieve the goals, on should write ad-hoc `visualize` method or use some of the hooks.
