### ISSUE TITLE
Refactor BaseDataset --> PythonDataset 

### ISSUE THREAD

**Issue by MarekSebo** [Cognexa/cxflow#125]
Depends on the development plan of CXFlow: If and only if we plan to implement support for other languages anytime soon is this issue relevant.

If we plan to implement other languages soon, then current _BaseDataset_ is a base dataset just for python and therefore should be renamed to _PythonDataset_ or _BasePythonDataset_

**Comment by petrbel** [comment]
Support of additional languages is already implemented. You can implement your dataset in any language you want, the only thing is that you have to compile it so that python can load it.

Note that other languages will not inherit from our datasets (instead, they will implement the provided interface of the abstract dataset).

Hence, the base dataset is actually really a base dataset for python datasets. Note that you can implement python dataset without using the base dataset as long as it implements the interface given by abstract dataset.

Any comments? @FloopCZ @blazekadam

**Comment by blazekadam** [comment]
I agree.
